### ISSUE TITLE
有需求否，嘤嘤嘤

### ISSUE THREAD

**Issue by chihuo2104** [GaisaiYuno/cdn#1]
# 我这里一个轻量正好闲着
# HongKong区的
# 帮你放点CDN也没什么问题

**Comment by GaisaiYuno** [comment]
不用了，就一个小小的gitalk.js，才100多k

**Comment by chihuo2104** [comment]
> 不用了，就一个小小的gitalk.js，才100多k

嘤嘤嘤，再见
